
POST https://localhost:5002/api/User/login
Content-Type: application/json

{
  "email": "lucas3@gmail.com",
  "password": "Lucas222"
}

###
GET https://localhost:5002/api/User
Content-Type: application/json

{
  "email": "seu_usuario",
  "password": "sua_senha"
}


