# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: volume-orderapi-sqlserver
# spec:
#   accessModes:
#     - ReadWriteOnce
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 4Gi
#   storageClassName: csi-hostpath-sc